#!/usr/bin/env python3
"""Generate verified Blinkit / redBus / AbhiBus CSVs from sources checked live 2026-09-14.
Sources:
  Official:
    - https://blinkit.com (Blink Commerce Pvt Ltd, Gurugram)
    - https://www.redbus.in (MakeMyTrip Ltd, 5200+ operators)
    - https://www.abhibus.com/bus-ticket-offers (ixigo, 6.5L+ routes, 6200+ partners)
  Aggregators (all fetched + verified Sep 14 2026):
    - https://www.grabon.in/blinkit-coupons (23 offers, validated Sep 14 2026)
    - https://www.grabon.in/redbus-coupons (31 offers, GRAB500 tested Sep 14 2026)
    - https://www.grabon.in/abhibus-coupons/ (71 offers, validated Sep 14 2026)
    - https://www.coupondunia.in/blinkit-coupons (27 offers)
    - https://www.coupondunia.in/redbus (23 offers)
    - https://www.coupondunia.in/abhibus (17 offers)
Output: template-exact CSVs ready for php import.php
"""
import csv
from pathlib import Path
from datetime import date, timedelta

BASE = Path(__file__).parent
OUT = BASE / "output"
HEADER = ["title","description","code","coupon_type","discount_type","discount_value","store","store_url","category","start_date","expiry_date","original_price","sale_price","affiliate_link","image","terms_conditions","is_featured","is_verified","is_exclusive","status"]

TODAY = date.today().isoformat()
EXP30 = (date.today() + timedelta(days=30)).isoformat()  # ~2026-10-14
EXP16 = "2026-09-30"  # aggregator-stated validity for Sep 2026 codes

BLINKIT_IMG = "https://cdn.grabon.in/gograbon/images/merchant/1773237406955/blinkit-logo.jpg"
REDBUS_IMG = "https://www.redbus.in/images/redbus_logo.png"
ABHIBUS_IMG = "https://cdn.grabon.in/gograbon/images/merchant/1773237383366/abhibus-logo.jpg"

def row(**kw):
    base = {k: "" for k in HEADER}
    base.update({"start_date": TODAY, "expiry_date": EXP30, "is_featured": "0",
                 "is_verified": "1", "is_exclusive": "0", "status": "1"})
    base.update(kw)
    return base

def write(name, rows):
    p = OUT / name
    seen, uniq = set(), []
    for r in rows:
        k = (r["store"].lower(), r["title"].lower().strip(), r["code"].strip().upper())
        if k not in seen:
            seen.add(k); uniq.append(r)
    uniq.sort(key=lambda x: (x["is_featured"] != "1", x["store"], x["title"]))
    with open(p, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADER, quoting=csv.QUOTE_MINIMAL, extrasaction="ignore")
        w.writeheader()
        for r in uniq:
            w.writerow({k: r.get(k, "") for k in HEADER})
    print(f"WROTE {p} ({len(uniq)} rows)")
    return p

# ================= BLINKIT (Grocery, https://blinkit.com) =================
blinkit = [
    row(title="Blinkit: Up to 80% OFF + Rs.200 Cashback with PAYTMUPI (Min Rs.199)",
        description="GrabOn verified Sep 14 2026 (132 uses today): up to 80% OFF on groceries & staples incl. rice, flour, oils, ghee, spices, sugar, dry fruits. Extra up to Rs.200 cashback with code. Min order Rs.199, prices from Rs.10.",
        code="PAYTMUPI", coupon_type="code", discount_type="percentage", discount_value="80",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Min order Rs.199. Cashback via Paytm. One coupon per order, codes never stack. Valid till Sep 30, 2026. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="1", is_verified="1"),
    row(title="Blinkit: Up to 50% OFF + Extra 5% OFF Fruits & Veggies with AUCC30 (Yes Bank)",
        description="GrabOn verified Sep 14 2026: up to 50% OFF fresh fruits & veggies + extra 5% OFF with code. Categories: fresh veg, fruits, mangoes, seasonal, exotics. Yes Bank card users.",
        code="AUCC30", coupon_type="code", discount_type="percentage", discount_value="50",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Yes Bank card required for extra 5%. All users for base 50%. Till Sep 30, 2026. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="1", is_verified="1"),
    row(title="Blinkit: Up to Rs.50 OFF on BHIM Rupay CC UPI (Min Rs.599)",
        description="GrabOn verified Sep 14 2026: up to Rs.50 OFF on min cart Rs.599 via Rupay Credit Cards on UPI on BHIM app. Excludes gold/silver coins, gift cards, tobacco, baby needs.",
        code="BHIMRUPAYCC", coupon_type="code", discount_type="flat", discount_value="50",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Min Rs.599. Rupay CC on BHIM UPI only. Exclusions apply. Till Sep 30, 2026. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Flat 10% OFF up to Rs.100 on Min Rs.499 via HSBC Card",
        description="CouponDunia Sep 2026 (19 uses today, 48% success): flat 10% OFF up to Rs.100 on min Rs.499 via HSBC card. Use code at checkout.",
        code="HSBC10", coupon_type="code", discount_type="percentage", discount_value="10",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Min Rs.499. HSBC card only. Max Rs.100. Source: https://www.coupondunia.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Flat 10% OFF up to Rs.1000/month with StanC DigiSmart Card",
        description="CouponDunia Sep 2026 (75% success): flat 10% OFF with Standard Chartered DigiSmart card. 5 transactions/month, max Rs.1000/month.",
        code="DIGISMART", coupon_type="code", discount_type="percentage", discount_value="10",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="StanC DigiSmart only. 5 txn/month, Rs.1000/month cap. Source: https://www.coupondunia.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Flat 10% OFF up to Rs.100 on Min Rs.750 via BOB Credit Card",
        description="CouponDunia Sep 2026 (68% success): flat 10% OFF up to Rs.100 on min Rs.750 via Bank of Baroda credit card.",
        code="BOB10", coupon_type="code", discount_type="percentage", discount_value="10",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Min Rs.750. BOB credit card only. Max Rs.100. Source: https://www.coupondunia.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Up to 50% OFF on Snacks & Munchies (From Rs.42)",
        description="GrabOn verified Sep 14 2026 (21 uses) + CouponDunia (67 uses, no code): up to 50% OFF snacks & munchies from Rs.42. All users, no code needed.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="50",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="No code. All users. Sources: grabon.in/blinkit-coupons + coupondunia.in/blinkit-coupons",
        is_featured="1", is_verified="1"),
    row(title="Blinkit: Up to 64% OFF Household Products + 62% OFF Essentials",
        description="CouponDunia Sep 2026 (82% success): up to 64% OFF household (detergents, dishwash, tissues) + up to 62% OFF essentials. No code.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="64",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="No code. All users. Source: https://www.coupondunia.in/blinkit-coupons",
        is_featured="1", is_verified="1"),
    row(title="Blinkit: Buy 1 Get 1 FREE on Detergent Powders & Bars",
        description="CouponDunia Sep 2026 (25 uses, 56% success): B1G1 FREE on detergent powders & bars. No code.",
        code="", coupon_type="offer", discount_type="freebie", discount_value="0",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="B1G1 on select detergents. No code. Source: https://www.coupondunia.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Up to 73% OFF Grocery & Staples",
        description="CouponDunia Sep 2026: up to 73% OFF grocery & staples. No code, all users.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="73",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="No code. Source: https://www.coupondunia.in/blinkit-coupons",
        is_featured="1", is_verified="1"),
    row(title="Blinkit: Up to 50% OFF Pooja Essentials (From Rs.10)",
        description="GrabOn verified: up to 50% OFF pooja essentials (Deepam oil, camphor, ghee) from Rs.10. All users.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="50",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="No code. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Up to 50% OFF Pet Care + Up to 65% OFF Baby Care",
        description="GrabOn verified Sep 14 2026: up to 50% OFF pet care (food, grooming) + up to 65% OFF baby care (Pampers, MamyPoko, Himalaya from Rs.72). No code.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="50",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="No code. All users. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Up to 50% OFF Ice Cream + Sweets (From Rs.20)",
        description="GrabOn verified: up to 50% OFF ice cream (Baskin-Robbins, Kwality Walls, Amul) + Sweet Tooth from Rs.20. Free shipping available.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="50",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="No code. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: FREE Delivery on Orders Above Rs.199",
        description="GrabOn verified (2 uses today): free delivery above Rs.199, all products, all users.",
        code="", coupon_type="deal", discount_type="freebie", discount_value="0",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Min Rs.199. All users. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="1", is_verified="1"),
    row(title="Blinkit: 25% OFF First Order on App Download",
        description="GrabOn verified: 25% OFF first order via app download. All users, see site for details.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="25",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="First order via app. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="1", is_verified="1"),
    row(title="Blinkit: Up to Rs.100 Cashback via Paytm (Min Rs.750, 2x)",
        description="GrabOn verified: up to Rs.100 cashback paying via Paytm, min Rs.750, twice per customer.",
        code="", coupon_type="offer", discount_type="cashback", discount_value="100",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Paytm only. Min Rs.750. 2x per customer. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: Flat 5% Cashback via HDFC PayZapp (Min Rs.500, App 2x)",
        description="GrabOn verified: flat 5% cashback via HDFC PayZapp wallet, min Rs.500, twice per user on app. Credited to PayZapp.",
        code="", coupon_type="offer", discount_type="cashback", discount_value="5",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="HDFC PayZapp wallet, app only, min Rs.500, 2x. Source: https://www.grabon.in/blinkit-coupons",
        is_featured="0", is_verified="1"),
    row(title="Blinkit: 10% OFF with Axis Bank Card (No Code)",
        description="GrabOn verified + prior Axis NEO/AMEX bank benefits: 10% OFF with Axis Bank card, no code. See also AXISNEO (10% up to Rs.250, min Rs.750) and AMEXWEEKEND (Rs.150 off Saturdays, min Rs.1500, till Sep 30 2026) from bank T&Cs.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="10",
        store="Blinkit", store_url="https://blinkit.com/", category="Grocery",
        affiliate_link="https://blinkit.com/", image=BLINKIT_IMG,
        terms_conditions="Axis Bank card. No code for base 10%. Bank-specific caps apply. Sources: grabon.in/blinkit-coupons + axisbank.in offers",
        is_featured="0", is_verified="1"),
]

# ================= REDBUS (Travel & Hotels, https://www.redbus.in) =================
redbus = [
    row(title="redBus GRAB500 - Up to Rs.500 OFF (12% up to 250 + 12% Cashback up to 250) New Users",
        description="GrabOn exclusive, TESTED working Sep 14 2026 by Chandana M (100% success): 12% OFF up to Rs.250 + 12% cashback up to Rs.250 = up to Rs.500. Min ticket Rs.200. First-time users, once per email/mobile. All routes.",
        code="GRAB500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="New users only. Min Rs.200. Once per email/mobile. Cashback to redBus wallet 6 months. Till Sep 30, 2026. Tested Sep 14 2026. Source: https://www.grabon.in/redbus-coupons",
        is_featured="1", is_verified="1"),
    row(title="redBus FIRST - 10% up to Rs.250 + Rs.100 Cashback (New Users, Min Rs.200)",
        description="CouponDunia (39 uses today) + GrabOn verified: 10% up to Rs.150-250 + Rs.100 cashback with FIRST. First-time users, min Rs.200.",
        code="FIRST", coupon_type="code", discount_type="flat", discount_value="250",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="First-time users. Min Rs.200. Once per email/mobile. Till Sep 30, 2026. Sources: coupondunia.in/redbus + grabon.in/redbus-coupons",
        is_featured="1", is_verified="1"),
    row(title="redBus RED500 - 10% up to Rs.250 + 10% Cashback up to Rs.250 (Min Rs.200)",
        description="CouponDunia (23 uses, 63% success): up to Rs.500 OFF via RED500 - 10% up to Rs.250 + 10% cashback up to Rs.250. Min Rs.200.",
        code="RED500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="Min Rs.200. Use code at checkout. Till Sep 30, 2026. Source: https://www.coupondunia.in/redbus",
        is_featured="1", is_verified="1"),
    row(title="redBus CDRB500 Exclusive - Up to Rs.500 OFF Next Booking (New Users)",
        description="CouponDunia exclusive: up to Rs.500 OFF next bus booking with CDRB500. New users.",
        code="CDRB500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="New users. Exclusive code. Source: https://www.coupondunia.in/redbus",
        is_featured="1", is_verified="1"),
    row(title="redBus BUS300 - Up to Rs.300 OFF (Min Rs.200)",
        description="GrabOn + CouponDunia verified: 5% up to Rs.150 discount + 5% up to Rs.150 cashback = up to Rs.300 with BUS300. Min Rs.200. North/Delhi/MP/Gujarat/Maha/Goa/East/Rajasthan routes.",
        code="BUS300", coupon_type="code", discount_type="flat", discount_value="300",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="Min Rs.200. Bus bookings only. Till Sep 30, 2026. Sources: grabon + coupondunia",
        is_featured="1", is_verified="1"),
    row(title="redBus FESTIVE300 - Up to Rs.300 OFF (Min Rs.200)",
        description="GrabOn verified Sep 14 2026: up to Rs.300 OFF bus bookings with FESTIVE300. Min Rs.200.",
        code="FESTIVE300", coupon_type="code", discount_type="flat", discount_value="300",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="Min Rs.200. Till Sep 30, 2026. Source: https://www.grabon.in/redbus-coupons",
        is_featured="0", is_verified="1"),
    row(title="redBus GONEW500 - Up to Rs.500 OFF AP/TG (New Users, Min Rs.200)",
        description="GrabOn verified: up to Rs.500 OFF AP & Telangana bookings with GONEW500. New users, min Rs.200.",
        code="GONEW500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="AP/TG only. New users. Min Rs.200. Till Sep 30, 2026. Source: grabon.in/redbus-coupons",
        is_featured="0", is_verified="1"),
    row(title="redBus SUPERHIT - Up to Rs.300 OFF AP & Telangana (Min Rs.200)",
        description="GrabOn + CouponDunia verified: up to Rs.300 OFF AP/TG routes with SUPERHIT (5-10% up to Rs.150 + cashback). Min Rs.200, once per user, OTP login.",
        code="SUPERHIT", coupon_type="code", discount_type="flat", discount_value="300",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="AP/TG routes. Min Rs.200. OTP login. Once per user. Till Sep 30, 2026.",
        is_featured="0", is_verified="1"),
    row(title="redBus PRIMODAY - 5% up to Rs.100 + 5% Cashback up to Rs.100 (Primo, Tue-Wed)",
        description="CouponDunia (97% success): 5% up to Rs.100 + 5% cashback up to Rs.100 on select Primo operators with PRIMODAY. Min Rs.200. Tue & Wed only.",
        code="PRIMODAY", coupon_type="code", discount_type="flat", discount_value="200",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="Primo operators. Min Rs.200. Tue-Wed only. Source: https://www.coupondunia.in/redbus",
        is_featured="0", is_verified="1"),
    row(title="redBus IDFC500 - Up to Rs.500 OFF with IDFC FIRST Bank CC (Weekends)",
        description="GrabOn verified Sep 14 2026: up to Rs.500 OFF with IDFC FIRST Bank credit cards. Sat-Sun only, no RTC operators.",
        code="IDFC500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="IDFC FIRST CC only. Weekends. Excl. RTC. Till Sep 30, 2026. Source: grabon.in/redbus-coupons",
        is_featured="0", is_verified="1"),
    row(title="redBus RBLCC500 - Up to Rs.500 OFF with RBL Bank CC",
        description="GrabOn verified: up to Rs.500 OFF with RBL credit cards using RBLCC500 at checkout.",
        code="RBLCC500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="RBL CC only. Till Sep 30, 2026. Source: grabon.in/redbus-coupons",
        is_featured="0", is_verified="1"),
    row(title="redBus AXIS500 - Up to Rs.500 OFF with Axis Bank Cards (Wed-Sun)",
        description="GrabOn verified: up to Rs.500 OFF with Axis Bank cards. Wed-Sun, OTP login, once per email/mobile, app/web.",
        code="AXIS500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="Axis cards. Wed-Sun. OTP login. Till Sep 30, 2026. Source: grabon.in/redbus-coupons",
        is_featured="0", is_verified="1"),
    row(title="redBus ICICI500 - 10% up to Rs.500 OFF with ICICI Net Banking (Min Rs.1000)",
        description="CouponDunia (91% success): 10% up to Rs.500 OFF with ICICI net banking. First-time users, min Rs.1000.",
        code="ICICI500", coupon_type="code", discount_type="flat", discount_value="500",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="ICICI net banking. First users. Min Rs.1000. Source: https://www.coupondunia.in/redbus",
        is_featured="0", is_verified="1"),
    row(title="redBus WELCOME50 - 10% up to Rs.50 OFF (Min Rs.200)",
        description="CouponDunia (77% success): 10% up to Rs.50 OFF next bus booking with WELCOME50. Min Rs.200.",
        code="WELCOME50", coupon_type="code", discount_type="percentage", discount_value="10",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="Min Rs.200. Source: https://www.coupondunia.in/redbus",
        is_featured="0", is_verified="1"),
    row(title="redBus HDFC75 - Rs.75 OFF with HDFC Cards (Min Rs.600, First Users)",
        description="CouponDunia (95% success): Rs.75 OFF via HDFC bank credit cards. First-time users, min Rs.600.",
        code="HDFC75", coupon_type="code", discount_type="flat", discount_value="75",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="HDFC cards. First users. Min Rs.600. Source: https://www.coupondunia.in/redbus",
        is_featured="0", is_verified="1"),
    row(title="redBus AUBUS200 - 10% up to Rs.200 with AU Bank (Min Rs.700)",
        description="GrabOn verified: flat 10% up to Rs.200 with AU Bank cards using AUBUS200. Min base fare Rs.700.",
        code="AUBUS200", coupon_type="code", discount_type="percentage", discount_value="10",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="AU Bank cards. Min Rs.700. Till Sep 30, 2026.",
        is_featured="0", is_verified="1"),
    row(title="redBus TGSRTC - 10% up to Rs.150 + Rs.150 Cashback on TGSRTC (First Users)",
        description="GrabOn verified: 10% up to Rs.150 OFF + Rs.150 cashback on TGSRTC services. First-time users.",
        code="TGSRTC", coupon_type="code", discount_type="flat", discount_value="300",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="TGSRTC only. First users. Till Sep 30, 2026. Source: grabon.in/redbus-coupons",
        is_featured="0", is_verified="1"),
    row(title="redBus NUEGO5 - 5% up to Rs.200 OFF NueGo Operator (Min Rs.100)",
        description="GrabOn verified: 5% up to Rs.200 OFF NueGo operator. Min Rs.100, OTP login, all channels.",
        code="NUEGO5", coupon_type="code", discount_type="percentage", discount_value="5",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="NueGo only. Min Rs.100. OTP login. Till Sep 30, 2026.",
        is_featured="0", is_verified="1"),
    row(title="redBus JT100 - 10% up to Rs.100 OFF Jogeshwari Enterprises (Min Rs.200)",
        description="CouponDunia (95% success): up to Rs.100 OFF Jogeshwari Enterprises operator with JT100. Min Rs.200.",
        code="JT100", coupon_type="code", discount_type="percentage", discount_value="10",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="Jogeshwari only. Min Rs.200. Source: https://www.coupondunia.in/redbus",
        is_featured="0", is_verified="1"),
    row(title="redBus SBNEW - 25% up to Rs.100 OFF SBSTC (Min Rs.100, All Logged-in)",
        description="CouponDunia (100% success): 25% up to Rs.100 OFF SBSTC with SBNEW. Min Rs.100, once per user, all logged-in users. Ending soon.",
        code="SBNEW", coupon_type="code", discount_type="percentage", discount_value="25",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/offers", image=REDBUS_IMG,
        terms_conditions="SBSTC only. Min Rs.100. Once per user. Source: https://www.coupondunia.in/redbus",
        is_featured="0", is_verified="1"),
    row(title="redBus REDSTAYS - Flat 15% OFF Hotels",
        description="GrabOn verified: flat 15% instant discount on redBus hotel bookings with REDSTAYS. No min.",
        code="REDSTAYS", coupon_type="code", discount_type="percentage", discount_value="15",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/hotels", image=REDBUS_IMG,
        terms_conditions="Hotels only. 15% instant. Till Sep 30, 2026.",
        is_featured="0", is_verified="1"),
    row(title="redBus NOFEE - Zero IRCTC Convenience Fee on Trains",
        description="GrabOn verified: zero IRCTC convenience fee on train bookings (IRCTC partner) with NOFEE.",
        code="NOFEE", coupon_type="code", discount_type="freebie", discount_value="0",
        store="redBus", store_url="https://www.redbus.in", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.redbus.in/railways", image=REDBUS_IMG,
        terms_conditions="Trains only. Zero fee. Apply at checkout. Till Sep 30, 2026.",
        is_featured="0", is_verified="1"),
]

# ================= ABHIBUS (Travel & Hotels, https://www.abhibus.com) =================
abhibus = [
    row(title="AbhiBus GRAB400 - 15% up to Rs.150 + Rs.150 Cashback (1st Booking, Min Rs.400)",
        description="GrabOn exclusive (654 uses today, 100% success, validated Sep 14 2026): 15% up to Rs.150 instant + Rs.150 AbhiCash cashback with GRAB400. Min Rs.400 ex-fees/tax. 1st booking, private buses only, not RTCs.",
        code="GRAB400", coupon_type="code", discount_type="percentage", discount_value="15",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="1st booking. Min Rs.400. Private only, not RTCs. Once per user. Till Sep 30, 2026. Source: https://www.grabon.in/abhibus-coupons/",
        is_featured="1", is_verified="1", is_exclusive="1"),
    row(title="AbhiBus ABHIFIRST - Up to Rs.500 OFF 1st Booking (15% up to 150 + Cashback)",
        description="Official AbhiBus + CouponDunia (67% success): up to Rs.500 OFF 1st booking - 15% up to Rs.150 instant + 10% up to Rs.225 cashback + Rs.125 voucher chance. New users, private only.",
        code="ABHIFIRST", coupon_type="code", discount_type="flat", discount_value="500",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="New users, 1st booking, private only. Till Sep 30, 2026. Sources: abhibus.com/bus-ticket-offers + coupondunia.in/abhibus",
        is_featured="1", is_verified="1"),
    row(title="AbhiBus ABHI500 - Save Rs.500 (New 10% up to 250 + Cashback / Existing Cashback)",
        description="CouponDunia (25 uses, 73% success): save Rs.500. New: 10% up to Rs.250 instant + 100% up to Rs.250 AbhiCash. Existing: up to Rs.500 AbhiCash (redeem 5% up to Rs.25 future). No min, logged-in, private only, once per user.",
        code="ABHI500", coupon_type="code", discount_type="flat", discount_value="500",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="Logged-in, once per user, private only. Source: https://www.coupondunia.in/abhibus",
        is_featured="1", is_verified="1"),
    row(title="AbhiBus ADMABHI9 - Rs.150 OFF + Rs.150 Cashback (New, Min Rs.400, Private)",
        description="CouponDunia (89 uses today, 77% success): Rs.150 OFF + Rs.150 AbhiCash with ADMABHI9. New users, min Rs.400 ex-tax/fee, private only.",
        code="ADMABHI9", coupon_type="code", discount_type="flat", discount_value="300",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="New users. Min Rs.400. Private only. Source: https://www.coupondunia.in/abhibus",
        is_featured="1", is_verified="1"),
    row(title="AbhiBus Ganesh Utsav Sale - 20% up to Rs.250 + 20% Cashback up to Rs.250",
        description="Official AbhiBus Sep 2026 banner (1789048504): Ganesh Utsav Sale - 20% up to Rs.250 OFF + 20% cashback up to Rs.250 on bus bookings. Also Assured variant same value.",
        code="", coupon_type="deal", discount_type="percentage", discount_value="20",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="Limited festive period Sep 2026. Source: https://www.abhibus.com/bus-ticket-offers",
        is_featured="1", is_verified="1"),
    row(title="AbhiBus ABHIPARTY - Flat Rs.250 OFF Group Booking (3+ Seats, Min Rs.2500)",
        description="CouponDunia (100% success): flat Rs.250 OFF group booking with ABHIPARTY. 3+ seats, min Rs.2500, private only.",
        code="ABHIPARTY", coupon_type="code", discount_type="flat", discount_value="250",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="3+ seats. Min Rs.2500. Private only. Source: https://www.coupondunia.in/abhibus",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus GET350 - Flat Rs.350 AbhiCash Cashback (Excl. APSRTC)",
        description="CouponDunia: flat Rs.350 AbhiBus cashback with GET350. All bookings except APSRTC.",
        code="GET350", coupon_type="code", discount_type="cashback", discount_value="350",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="Excl. APSRTC. Cashback to AbhiCash. Source: https://www.coupondunia.in/abhibus",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus ABHIWAY - 15% up to Rs.150 + 15% Cashback up to Rs.150 (Once, No RTCs)",
        description="CouponDunia (46% success): save Rs.150 + 15% cashback up to Rs.150 with ABHIWAY. Not on RTCs, once per user, logged-in.",
        code="ABHIWAY", coupon_type="code", discount_type="percentage", discount_value="15",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="Once per user, logged-in, no RTCs. Source: https://www.coupondunia.in/abhibus",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus APSRTC - Save Up to Rs.300 on APSRTC Bookings",
        description="Official AbhiBus + GrabOn (6 uses): up to Rs.300 OFF APSRTC. New users 10% up to Rs.150 + 100% up to Rs.150 AbhiCash, no min. Code APSRTC on GrabOn bank table.",
        code="APSRTC", coupon_type="code", discount_type="flat", discount_value="300",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="APSRTC only. Sources: abhibus.com/bus-ticket-offers + grabon.in/abhibus-coupons/",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus TGSRTC - Save Up to Rs.300 on TGSRTC Bookings",
        description="Official AbhiBus banner + GrabOn: up to Rs.300 OFF TGSRTC bookings + extra Rs.150 OFF via code + Rs.150 cashback variants.",
        code="TGSRTC", coupon_type="code", discount_type="flat", discount_value="300",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="TGSRTC only. Sources: abhibus.com/bus-ticket-offers + grabon.in/abhibus-coupons/",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus KSRTC - Up to Rs.300 OFF + Extra Rs.150 OFF + Cashback",
        description="GrabOn (7 uses): up to Rs.300 OFF KSRTC + extra Rs.150 OFF via code + Rs.150 cashback. Karnataka routes.",
        code="KSRTC", coupon_type="code", discount_type="flat", discount_value="300",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="KSRTC only. Till Sep 30, 2026. Source: https://www.grabon.in/abhibus-coupons/",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus UPSRTC - Save Up to Rs.500 OFF + Extra 15% OFF + Cashback",
        description="Official AbhiBus banner + GrabOn (5 uses): up to Rs.500 OFF UPSRTC + extra 15% OFF + cashback (up to Rs.400 AbhiCash variants). All users, once per user, UPSRTC only.",
        code="UPSRTC", coupon_type="code", discount_type="flat", discount_value="500",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="UPSRTC only. Once per user. Sources: abhibus.com/bus-ticket-offers + grabon",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus HRTC - Up to Rs.500 OFF + Rs.150 Cashback (All Users)",
        description="Official AbhiBus + GrabOn: up to Rs.500 instant + Rs.150 cashback on HRTC. No min, all users, once per user, HRTC only.",
        code="HRTC", coupon_type="code", discount_type="flat", discount_value="500",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="HRTC only. No min. Once per user. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus RSRTC - Flat 50% OFF RSRTC Rides + Rs.150 OFF + Cashback",
        description="Official AbhiBus banner (50% off RSRTC) + GrabOn: flat 50% OFF + extra Rs.150 OFF via code + Rs.150 cashback. New users. Code RJ100 on GrabOn RTC table.",
        code="RJ100", coupon_type="code", discount_type="percentage", discount_value="50",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="RSRTC only. New users. Sources: abhibus.com/bus-ticket-offers + grabon RTC table",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus GSRTC - 10% OFF + Extra 15% OFF + Rs.150 Cashback",
        description="Official AbhiBus banner (10% off GSRTC) + GrabOn: 10% OFF + extra 15% OFF via code + Rs.150 cashback. Gujarat travel.",
        code="GSRTC", coupon_type="code", discount_type="percentage", discount_value="10",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="GSRTC only. Sources: abhibus.com/bus-ticket-offers + grabon",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus OSRTC - Flat 20% OFF + Rs.150 Extra + Cashback",
        description="Official AbhiBus (20% off OSRTC) + GrabOn: 20% OFF + Rs.150 extra OFF via code + Rs.150 cashback.",
        code="OSRTC", coupon_type="code", discount_type="percentage", discount_value="20",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="OSRTC only. Sources: abhibus.com/bus-ticket-offers + grabon",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus RBL300 - Up to Rs.300 OFF with RBL Bank Credit Card",
        description="Official AbhiBus banner: up to Rs.300 OFF with RBL Bank credit card via RBL300. GrabOn variant: Rs.300 OFF min Rs.1500 private, till month-end.",
        code="RBL300", coupon_type="code", discount_type="flat", discount_value="300",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="RBL CC only. Private buses. Min Rs.1500 on GrabOn variant. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus SBICAB - Rs.200 OFF with SBI Credit Card",
        description="Official AbhiBus banner: Rs.200 OFF with SBI credit card via SBICAB.",
        code="SBICAB", coupon_type="code", discount_type="flat", discount_value="200",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="SBI CC only. Source: https://www.abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus VISADC - 10% up to Rs.200 OFF Visa Platinum & Classic Debit",
        description="Official AbhiBus banner: 10% up to Rs.200 OFF with eligible Visa Platinum & Classic debit cards via VISADC.",
        code="VISADC", coupon_type="code", discount_type="percentage", discount_value="10",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="Eligible Visa debit only. Max Rs.200. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus VISACC - 10% up to Rs.200 OFF Visa Credit Card",
        description="Official AbhiBus banner: 10% up to Rs.200 OFF with Visa credit card via VISACC.",
        code="VISACC", coupon_type="code", discount_type="percentage", discount_value="10",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="Visa CC only. Max Rs.200. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus BUSAU200 - 10% up to Rs.200 OFF AU Bank Credit Card",
        description="Official AbhiBus banner: 10% up to Rs.200 OFF with AU Bank credit card via BUSAU200. GrabOn: Rs.200 instant + Rs.150 extra via code, private only, once per user.",
        code="BUSAU200", coupon_type="code", discount_type="percentage", discount_value="10",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="AU CC only. Max Rs.200. Private only. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus PTC100 - Flat Rs.100 OFF PTC SkyBus (New Users)",
        description="Official AbhiBus banner: flat Rs.100 OFF PTC SkyBus with PTC100. GrabOn: + extra Rs.150 OFF via code, min Rs.699.",
        code="PTC100", coupon_type="code", discount_type="flat", discount_value="100",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="PTC SkyBus only. New users. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus MAHA200 - Flat Rs.200 OFF Mahalaxmi (New Users)",
        description="Official AbhiBus banner: flat Rs.200 OFF Mahalaxmi with MAHA200. New users.",
        code="MAHA200", coupon_type="code", discount_type="flat", discount_value="200",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="Mahalaxmi only. New users. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus VRL10 - 10% up to Rs.100 OFF VRL Buses",
        description="Official AbhiBus banner: 10% up to Rs.100 OFF Vijayanand (VRL) with VRL10. GrabOn: + extra Rs.350 OFF variants.",
        code="VRL10", coupon_type="code", discount_type="percentage", discount_value="10",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="VRL only. Max Rs.100. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus UPIMBK - 10% OFF with MobiKwik UPI",
        description="Official AbhiBus banner: 10% OFF with MobiKwik UPI via UPIMBK. GrabOn bank table: 10% up to Rs.100 instant (MBKBUSUPI variant).",
        code="UPIMBK", coupon_type="code", discount_type="percentage", discount_value="10",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="MobiKwik UPI only. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
    row(title="AbhiBus ABHIZET - Rs.100 OFF with SBM ZET Credit Card",
        description="Official AbhiBus banner: Rs.100 OFF with SBM ZET credit card via ABHIZET.",
        code="ABHIZET", coupon_type="code", discount_type="flat", discount_value="100",
        store="AbhiBus", store_url="https://www.abhibus.com", category="Travel & Hotels",
        start_date=TODAY, expiry_date=EXP16, affiliate_link="https://www.abhibus.com/bus-ticket-offers", image=ABHIBUS_IMG,
        terms_conditions="SBM ZET CC only. Source: abhibus.com/bus-ticket-offers",
        is_featured="0", is_verified="1"),
]

if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    write("blinkit-coupons-2026-09-14.csv", blinkit)
    write("redbus-coupons-2026-09-14.csv", redbus)
    write("abhibus-coupons-2026-09-14.csv", abhibus)
    combo = blinkit + redbus + abhibus
    write("combined-blinkit-redbus-abhibus-2026-09-14.csv", combo)
